apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  ports:
  -name: {{ .Values.metadata.name }}{{ .Values.metadata.portType | lower | substr 4 8 }}
    port: {{ .Values.service.port }}
    protocol: {{ .Values.metadata.protocol }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.metadata.name }}
    type: {{ .Values.metadata.type }}
  type: {{ .Values.metadata.portType }}
status:
  loadBalancer: {}
